### ISSUE TITLE
avoid initial distribution artifacts

### ISSUE THREAD

**Issue by solraun** [konradha/statphys-proj#5]
the radial distribution is an average over the whole runtime, so initial distribution artifacts are still visible after the whole simulation. it would make more sense to let the simulation settle for ~100 steps, then making another run from that distribution.
or we could implement that the radial distribution is only averaged over the last 100 time steps. would probably make more sense

**Comment by solraun** [comment]
closed with newest interface branch: only the last 30 timesteps are considered

**Comment by konradha** [comment]
Closed w latest commit in interface branch.
